<<<<<<< HEAD
version: 0.0
os: linux

files:
  - source: /
    destination: /opt/creditportal/deploy

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/healthcheck.sh
      timeout: 60
      runas: root
=======
version: 0.0
os: linux

files:
  - source: /
    destination: /opt/creditportal/deploy

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/healthcheck.sh
      timeout: 60
      runas: root
>>>>>>> 1a2cf171db39c88df5840687e8104ec3161e72df
