version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 18

  build:
    commands:
      - echo "Build backend"
      - mvn -f backend/api-gateway/pom.xml clean package -DskipTests
      - mvn -f backend/auth-service/pom.xml clean package -DskipTests
      - mvn -f backend/customer-service/pom.xml clean package -DskipTests
      - mvn -f backend/creditcard-service/pom.xml clean package -DskipTests
      - mvn -f backend/transaction-service/pom.xml clean package -DskipTests

      - echo "Build frontend"
      - cd frontend
      - npm ci
      - npm run build
      - cd ..

      - mkdir -p artifacts/jars artifacts/ui
      - cp backend/api-gateway/target/*.jar artifacts/jars/api-gateway.jar
      - cp backend/auth-service/target/*.jar artifacts/jars/auth-service.jar
      - cp backend/customer-service/target/*.jar artifacts/jars/customer-service.jar
      - cp backend/creditcard-service/target/*.jar artifacts/jars/creditcard-service.jar
      - cp backend/transaction-service/target/*.jar artifacts/jars/transaction-service.jar
      - cp -r frontend/dist/* artifacts/ui/ || true
      - cp -r frontend/build/* artifacts/ui/ || true

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - artifacts/**/*
